### ISSUE TITLE
Créer un système d'authentificaction avec MongoDB

### ISSUE THREAD

**Issue by ADecametre** [ADecametre/H24-204-GR1-HandSpeak#12]
## Tâches
Ceci est une première estimation des étapes nécessaires à la réalisation de ce système.
Cette liste pourrait changer en tout temps.
- [x] Créer un compte MongoDB
- [x] Établir une connexion sécurisée entre Next.js et MongoDB
- [x] Créer un compte Clerk
- [x] Ajouter des _providers_ (Credentials, Email, Google, etc.)
- [x] Créer des pages brouillon pour tester les fonctionnalités (connexion, inscription, accès aux informations du compte)
- [x] Créer un _Middleware_ pour protéger les pages auquelles un utilisateur non-authentifié ne doit pas accéder
- [x] Lier les utilisateurs Clerk à MongoDB
- [ ] Créer des méthodes sécurisées (_Server Actions_) pour lire et écrire des données MongoDB

## Documentation utile
> [!NOTE]
> **Changement de plan :** finalement, à la place de NextAuth, nous allons utiliser [Clerk](https://clerk.com/docs), qui diminue le nombre d'étapes et qui va beaucoup faciliter le reste des étapes mentionnées ci-dessus, en suivant [ce tutoriel](https://github.com/ADecametre/H24-204-GR1-HandSpeak/issues/12#issuecomment-2073246253).

> [!NOTE]
> **Deuxième changement de plan :** finalement, à la place de Mongoose, on va utiliser [Prisma](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/mongodb-typescript-mongodb).
 - [Authenticated data access using Clerk, Prisma, and MongoDB - A post-making fullstack app](https://clerk.com/blog/clerk-prisma-mongodb-fullstack-post-app)
 - [Integrations: Sync Clerk data to your backend with webhooks](https://clerk.com/docs/integrations/webhooks/sync-data)
 - [Best practice for instantiating Prisma Client with Next.js | Prisma Documentation](https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices)

<br></br>
- <sup><sub>~~[Learn Next.js: Adding Authentication | Next.js](https://nextjs.org/learn/dashboard-app/adding-authentication)~~</sub></sup>
  - <sup><sub>~~Se baser surtout sur ce guide, puisqu'il s'agit de l'approche (avec NextAuth) recommandée par le site officiel de Next.js.~~</sub></sup>
  - <sup><sub>~~Par contre, pour stocker les informations, il utilise PostgreSQL.~~
  <sup><sub>~~Liens potentiellement utiles :~~</sub></sup>
    - <sup><sub>~~[@auth/mongodb-adapter | Auth.js](https://authjs.dev/reference/adapter/mongodb) (adaptateur MongoDB pour NextAuth)~~</sub></sup>
    - <sup><sub>~~[Learn Next.js: Setting Up Your Database | Next.js](https://nextjs.org/learn/dashboard-app/setting-up-your-database) (connecter une base de donnée avec Vercel)~~</sub></sup>
- <sup><sub>~~[Next.js Demystified: User Authentication with NextJS & MongoDB | by Rushabh Dabhade | Medium](https://medium.com/@Rushabh_/next-js-demystified-user-authentication-with-nextjs-mongodb-2a0e1e697526)~~</sub></sup>
  - <sup><sub>~~Ce guide utilise MongoDB (à l'aide de Mongoose, qui rajoute des fonctionnalités utiles).~~</sub></sup>
  - <sup><sub>~~Par contre, ce guide utilise une approche très différente (sans NextAuth) et il y a plusieurs choses qui sont mal faites.~~</sub></sup>
  - <sup><sub>~~Utiliser seulement les sections spécifiques à MongoDB (si on veut utiliser Mongoose, il faudra savoir l'utiliser en même temps que NextAuth).~~</sub></sup>

> [!CAUTION]
> Il faut chercher des guides récents, qui utilisent Next.js 13 (octobre 2022) et Next.js 14 (octobre 2023) avec leurs toutes dernières fonctionnalités (App Router, Server Actions).
> Beaucoup de guides et d'exemples en ligne utilisent le Pages Router (notre projet est configuré avec le nouveau App Router, qui comporte beaucoup de différences).

**Comment by ADecametre** [comment]
0e60c5a4cbea7df5d442fd666a571545ee7d726a
![image](https://github.com/ADecametre/H24-204-GR1-HandSpeak/assets/66925945/f5cc5669-d123-44bb-b465-c91f4d3cc205)

**Comment by norththinker** [comment]
Voici le tutoriel utilisé pour intégrer Clerck dans notre projet :  https://www.youtube.com/watch?v=O5cmLDVTgAs

**Comment by ADecametre** [comment]
74c562f034af0084f49cca0a8f78ca5c5cb1b21a

https://github.com/ADecametre/H24-204-GR1-HandSpeak/assets/66925945/c7c4f787-b7ef-44ed-b761-08d1f87ad1d0
